# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-07 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('transaction_from_user_id', models.IntegerField(default=0)),
                ('transaction_amount', models.IntegerField(default=0)),
                ('transaction_type', models.CharField(max_length=256)),
                ('cash_type', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
