# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-08 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='category',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='games',
            name='target',
            field=models.IntegerField(default=0),
        ),
    ]
